### PR TITLE
Remove unused translations

### PR DESCRIPTION
**Pull request by dnicolson**
This pull request removes translation keys that appear to be unused. The removed keys no longer exist in the `ui/src` directory and some seem to have been removed in 178fbb34efbea31a5adec44cc9f66982695fba1b.

### CODE REVIEW

**Comment by bwp91** [comment]
Seems a shame to lose these translations, in case they were ever needed in the future

**Comment by dnicolson** [comment]
@bwp91 I wouldn't say they would be lost, the git history is always there.

Also, a quick `git log -S"label_upgrade"` shows that since "Upgrade" was replaced by "Update" in 4f4310fbb5999e6817afc5ebf7fcdd8db04ee7bc it's been unnecessarily translated into an additional 29 languages.

**Comment by bwp91** [comment]
not sure why this build is failing, @dnicolson could you try rebasing against branch`beta-4.50.5` hopefully this will kick off the checks again

**Comment by dnicolson** [comment]
If this needs to be rebased again, this should do the trick from the `i18n` directory:

```bash
UNUSED_TRANSLATION_KEYS=(
  accessories.control.label_set_to
  accessories.control.not_supported
  config.button_backup
  login.title_login
  platform.docker.settings.message_image_upgrade_required
  platform.docker.settings.title_settings
  platform.docker.settings.toast_container_restart_required
  platform.docker.settings.toast_title_settings_saved
  plugins.label_certified_plugin
  plugins.manage.label_homebridge_upgraded
  plugins.manage.label_upgrade
  reset.label_reset_homebridge
  reset.title_force_restart_hb_service_short
  status.homebridge.label_version
  status.memory.label_used
  status.services.label_console
  status.services.label_listening_on_port
  status.services.title_services
  status.title_server_status
  status.uptime.label_days
  status.uptime.label_hours
  status.uptime.label_minutes
  status.widget.label_widget_has_no_options
  status.widget.systeminfo.label_npm_version
  users.toast_failed_to_update_user
)

for lang in `ls`; do
  for key in ${UNUSED_TRANSLATION_KEYS[*]}; do
     grep -v $key $lang > $lang.tmp && mv $lang.tmp $lang
  done
done
```

**Pull request closed without merging**
