### PR TITLE
Style Changes to Increase Visibility of Temperatures

### PR DESCRIPTION
**Pull request by mcmspark**
On small displays the temperature is hard to read.  This increases the size of the fonts and expands the width of the temperature circle on accessory widgets.

Screen Shot 2022-03-13 at 3 57 38 PM
Screen Shot 2022-03-13 at 4 00 56 PM

(I did accidentally use a work github account initially to apply and then revert the change)

### CODE REVIEW

**Comment by Feilner** [comment]
Personally I prefer the version with the circle as it is in line with the home app design. But I agree that on small displays it's not as easy to see as in the home app. I would recommend to change to a better readable font or bold format. 

imageimage


If readability on small displays also the humidity visualization needs to be updated. 
image

Another option would be to offer different visualizations and let the user choose.

**Comment by mcmspark** [comment]
I did consider a larger change to allow skins and custom styles, but it is unclear if that is a desired outcome here, as it could give rise to a diverse user experience.

**Comment by bwp91** [comment]
Personally I like this update. Makes the temperature (and humidity @mcmspark I assume is the same?) clearer.

> Personally I prefer the version with the circle as it is in line with the home app design

I also understand this opinion, but (im having to think about this!) the homebridge ui was always meant as a helpful tool for homebridge rather than a 'replacement' for the home app.

any opinion @NorthernMan54 , this is considering this PR is still something to look at and also would need to be rebased against master branch.

**Comment by NorthernMan54** [comment]
@bwp91 - Why don't we release this as part of the beta, and collect feedback from the wider user community.  Personally I prefer the larger fonts as they are easier to read.   And am thinking we leave the humidity characteristic for a further release during the beta.  This will allow for a direct comparison.

PS - I'm like you and rarely use the accessories tab, except for troubleshooting issues.

**Comment by bwp91** [comment]
Hi @mcmspark happy to put this into a beta version. I have rebasd this already onto a beta branch.

My last question is - are the screenshots needed as part of the PR, or can these be binned?

**Comment by donavanbecker** [comment]
We could make this an option with config ui options? So we could keep both sides happy. Thoughts?

**Comment by bwp91** [comment]
@donavanbecker my thought on this is to not have a config option. don't wanna open a can of worms on this - for me the least number of config options the better.
I personally like these changes. I think putting this into a beta release would be great.
But i do think the screenshots as part of this PR are not needed.

**Comment by mcmspark** [comment]
Thanks Ben, it is so long ago.  I thought I posted screenshots with the PR.  I can look if I still have them.



Sent from my iPhone

On Jul 19, 2023, at 8:42 PM, Ben ***@***.***> wrote:

﻿

Hi @mcmspark<https://github.com/mcmspark> happy to put this into a beta version. I have rebasd this already onto a beta branch.

My last question is - are the screenshots needed as part of the PR, or can these be binned?

**Comment by bwp91** [comment]
> Thanks Ben, it is so long ago.  I thought I posted screenshots with the PR.  I can look if I still have them.

I mean - the screenshots were helpful to see what this PR was gonna do, but I don't this that they need to be part of the PR files

**Comment by mcmspark** [comment]
I do love options.  As long as it is clear how and what to choose.



On Jul 19, 2023, at 9:36 PM, Donavan Becker ***@***.***> wrote:

﻿

We could make this an option with config ui options? So we could keep both sides happy. Thoughts?

**Comment by donavanbecker** [comment]
@mcmspark We don’t need options just thought I would throw it out there.

**Comment by donavanbecker** [comment]
I think once the screenshots are removed from the PR we would be good to go to merge this.

**Comment by bwp91** [comment]
@mcmspark i'm quite looking forward to this PR and trying it out with my very disorganised homebridge ui!
once the screenshots are removed we can look to merge in 🚀

**Comment by donavanbecker** [comment]
@mcmspark please remove screenshots so we can merge this.

**Pull request closed without merging**
