### PR TITLE
Fixed nested arrays settings

### PR DESCRIPTION
**Pull request by Slonick**
## :recycle: Current situation

*Nested arrays display only one element.*

## :bulb: Proposed solution

*To solve the problem, the generated layout and data are matched.*

## :gear: Release Notes

*The fix is applied only if `"fixArrays": true` is added to config.schema.json.*
For example: 
`
{
 "pluginAlias": "examplePluginAlias",
 "pluginType": "platform",
 "singular": true,
 "fixArrays": true,
 "schema": {...}
}`

### CODE REVIEW

**Comment by donavanbecker** [comment]
Please re-branch to beta branch

**Comment by bwp91** [comment]
Hi @Slonick 
could you show a screenshot of how this would look in the ui?
My opinion personally (not necessarily homebridge-opinion!) is that it would be nice to avoid extra options like `fixArrays` in the config, I totally appreciate why you have added this, assuming for backward compatibility?

**Comment by grzegorz914** [comment]
@donavanbecker , @bwp91  

Why this can not be merged, if you use tab array in layout then only one element is displayed however many are configured, I think this resolve this:
https://github.com/grzegorz914/homebridge-denon-tv/issues/92
and this:
https://github.com/grzegorz914/homebridge-lgwebos-tv/issues/95

**Comment by donavanbecker** [comment]
@bwp91 I would agree with @grzegorz914. I have experienced this issue as well.

**Review by donavanbecker — APPROVED** [review]

**Comment by donavanbecker** [comment]
@Slonick Once merged can you also add something to config wiki explaining this?

**Comment by Slonick** [comment]
> @Slonick Once merged can you also add something to config wiki explaining this?

This fix requires additional testing, I checked on my plugin and on 1-2 more from open issues, so I added a separate flag. Later it will not be needed, so I think it makes no sense to describe it in the wiki.

**Comment by donavanbecker** [comment]
@Slonick Okay so this PR isn’t ready?

**Comment by donavanbecker** [comment]
Pull Requests

**Comment by Slonick** [comment]
> Pull Requests

no, it's ready for pull request. It's not ready for release. I need feedback that it works. And it works not only for nested arrays, but also does not break anything on regular configs using the `"fixArrays": true`.

**Comment by donavanbecker** [comment]
@Slonick New beta should be published shortly

**Comment by donavanbecker** [comment]
@Slonick Eslint failed. Can you submit another Pull Request? 

https://github.com/homebridge/homebridge-config-ui-x/actions/runs/5601841759/jobs/10246388470#step:5:1

**Comment by Slonick** [comment]
> @Slonick Eslint failed. Can you submit another Pull Request?
> 
> https://github.com/homebridge/homebridge-config-ui-x/actions/runs/5601841759/jobs/10246388470#step:5:1

yes i will do it soon

**Comment by donavanbecker** [comment]
test.5 has been released.

**Comment by donavanbecker** [comment]
@Slonick, so `"fixArrays": true` just needs to be added to the base of config.schema.json? So right after this line: https://github.com/0x5e/homebridge-tuya-platform/blob/fd48de4007918b32be22045e5b6a20121b69e178/config.schema.json#L4

**Comment by Slonick** [comment]
> @Slonick, so `"fixArrays": true` just needs to be added to the base of config.schema.json? So right after this line: https://github.com/0x5e/homebridge-tuya-platform/blob/fd48de4007918b32be22045e5b6a20121b69e178/config.schema.json#L4

yes, that's right, and after that the arrays should be displayed correctly

**Comment by donavanbecker** [comment]
Screenshot 2023-07-19 at 5 50 14 PM
I just tested this out with out luck. I will try it under the Array.

**Comment by donavanbecker** [comment]
no luck moving it to another section

**Comment by Slonick** [comment]
@donavanbecker Are we talking about the same issue? If you look at my screenshot from the second version of pull request, then there is MacBook and PC, before the fix the tab from the PC was not displayed.

**Comment by Slonick** [comment]
if you have duplicate data or data is not displayed, but it is in config, then I need name of plugin and your current config, and tomorrow I will check it.

**Comment by donavanbecker** [comment]
Yes it does look the same.

Plugin: https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/config.schema.json
Config:
```
{
            "name": "Tuya",
            "options": {
                "projectType": "2",
                "accessId": "xxxxxxxxxxxx",
                "accessKey": "xxxxxxxxxxxxxxxxxxxxxxxx",
                "countryCode": 1,
                "username": "email@email.com",
                "password": "password",
                "appSchema": "tuyaSmart",
                "homeWhitelist": [
                    12345678
                ],
                "deviceOverrides": [
                    {
                        "id": "global",
                        "unbridged": true,
                        "schema": [
                            {
                                "code": "motion_switch",
                                "hidden": true
                            },
                            {
                                "code": "floodlight_switch",
                                "hidden": true
                            },
                            {
                                "code": "floodlight_lightness",
                                "hidden": true
                            }
                        ]
                    }
                ],
                "debug": true
            },
            "platform": "TuyaPlatform"
        },
```

**Comment by bwp91** [comment]
I haven’t tested this - but hypothetically (i know it’s already been merged) what would happen if this PR didn’t have the config option and it were to be merged without the config option?

**Comment by grzegorz914** [comment]
I have tested this on my plugins and looks like all is correct now, before was only 1 element visible.

**Comment by donavanbecker** [comment]
@grzegorz914, what change did you have to make?

**Comment by grzegorz914** [comment]
@donavanbecker 
I have added to my config.schema  `„fixArrays”: true`, before apply the fix `TabArray` displayed only 1 element, now displays all as you can see on the screenshot. This problem was if you use config.schema with layout.

**Comment by Slonick** [comment]
> Screenshot 2023-07-19 at 5 50 14 PM I just tested this out with out luck. I will try it under the Array.

image

i fixed it

**Pull request merged**
